### ISSUE TITLE
Add `konnect.entityID` to allow adopting existing entities from Konnect

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-configuration#232]
## Problem Statement

From https://github.com/Kong/gateway-operator/issues/460 to adopt existing entities in Konnect. 
We should define a `spec.konnect.entityID` to enable users to adopt an existing entity in Konnect with the specified ID. Based on the field, we should also define validation rules (present only controlled by Konnect Entity controller; immutable after progammed; ...).

## Proposed Solution

Define a `KonnectAttributes` type including the `EntityID` field, and add the field in the `spec` of all CRDs supported in the Konnect entity controller. 
Also we need to add at least the following rules on the field:
- Can only be present when its `controlPlaneRef` is pointing to a Konnect Control plane
- Be immutable when the resource is "Programmed", which means that the resource is already associated with a Konnect entity

## Acceptance Criteria

- [ ] `konnect.entityID` is present in each CRD we support in Konnect entity controller
- [ ] Have the validation rules (CELs) to check the field
  - [ ] Can only be present when its `controlPlaneRef` is pointing to a Konnect Control plane
  - [ ] Cannot be added, modified or unset when the resource is "Programmed" (pointing to a Konnect entity)

**Comment by pmalek** [comment]
`konnect.entityID` might be a bit ambiguous: users might take it as "when creating this resource, set this ID".

How about:

```
spec:
  konnect:
    adopt:
      by: id # to allow interface extension in the future 
      id: <id_to_adopt>
```

or

```

spec:
  konnect:
    adoptId: <id_to_adopt>
```

WDYT?

**Comment by randmonkey** [comment]
I think the former one
```yaml
spec:
  konnect:
    adopt:
      by: id # to allow interface extension in the future 
      id: <id_to_adopt>
```
would make more sense, since @czeslavo has some thoughts of options of not changing the Konnect entity when it is not the same as the spec. This provides room for extensions.

**Comment by czeslavo** [comment]
How about making the strategy a parameter so it's clear what will be the behavior?

```yaml
spec:
  konnect:
    adoption: # to use nouns instead of verbs
      strategy: OverrideKonnectConfig # possible alternatives could be 'HaltOnKonnectConfigMismatch' or 'AdoptKonnectConfig'
      id: <id_to_adopt>
```
